name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

permissions:                    # Global permissions configuration starts here
  contents: write                # 'write' access to repository contents
  pull-requests: write          # 'write' access to pull requests

jobs:
  

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Install flamegraph dependencies
      run: apt-get install linux-tools-common linux-tools-generic linux-tools-`uname -r`

    - name: Build
      run: cargo build --profile=release --verbose
    - name: Run Clippy
      run: cargo clippy --all-targets --all-features
    - name: Run tests
      run: cargo test --profile=release --verbose

    - name: Run as release to update readme
      run: cargo run --profile=release update-readme

    - name: Commit files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -a -m "Update ReadMe"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
